name: MinecraftSurvivalTeamsPlugin
version: ${project.version}
main: me.damascus2000.minecraftsurvivalteamsplugin.Main
api-version: 1.13
author: Damascus20000
description: A minecraft survival plugin including Teams
commands:
  travel:
    description: Opens the Travel menu
    usage: /<command>
  teams:
    description:
      usage /teams
  teamchat:
      description:
        usage /teamchat
permissions:
  teams.*:
    description: Gives acces to all team commands
    children:
      teams.create: true
      teams.join: true
      teams.leave: true
      teams.kick: true
      teams.remove: true
      teams.chat: true
  teams.normal:
    children:
      teams.create: true
      teams.join: true
      teams.leave: true
      teams.chat: true
  teams.create:
    description: Gives acces to the /teams create command
    default: true
  teams.join:
    description: Gives acces to the /teams join command
    default: true
  teams.leave:
    description: Gives acces to the /teams leave command
    default: true
  teams.kick:
    description: Gives acces to the /teams kick command
    default: false
  teams.remove:
    description: Gives acces to the/teams remove command
    default: true
  teams.chat:
    description: Gives acces to the /teamchat command
    default: true